version: '3'
    
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=merger
      - POSTGRES_USER=merger
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  web:
    build: .
    command: bash -c "python manage.py migrate; python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - WEB_PASSWORD=${WEB_PASSWORD}
    depends_on:
      - db