# Generated by Django 3.0.3 on 2020-05-02 23:05

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('service_name', models.CharField(blank=True, max_length=50)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('protocol', models.IntegerField(choices=[(6, 'TCP'), (17, 'UDP')], default=6)),
                ('is_web_app', models.BooleanField()),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['protocol', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Proj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('org_name', models.CharField(blank=True, max_length=50)),
                ('init_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-init_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=50, verbose_name='IP Address')),
                ('fqdn', models.CharField(blank=True, max_length=50, verbose_name='FQDN')),
                ('os', models.CharField(blank=True, max_length=50, verbose_name='OS')),
                ('version', models.CharField(blank=True, max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('proj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Proj')),
            ],
            options={
                'ordering': ['ip_address', 'fqdn'],
            },
        ),
        migrations.CreateModel(
            name='WebApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('programing_lang', models.CharField(blank=True, max_length=50)),
                ('programing_framework', models.CharField(blank=True, max_length=50)),
                ('root_url', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Port')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('path', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('webapp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.WebApp')),
            ],
        ),
        migrations.CreateModel(
            name='Vuln',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('cve', models.CharField(max_length=20, null=True)),
                ('score', models.FloatField()),
                ('risk', models.IntegerField(choices=[(0, 'Info'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=0)),
                ('description', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.App')),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Port')),
                ('proj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Proj')),
                ('sys', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Sys')),
                ('webapp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.WebApp')),
                ('webpage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.WebPage')),
            ],
            options={
                'ordering': ['-risk'],
            },
        ),
        migrations.AddField(
            model_name='port',
            name='sys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Sys'),
        ),
        migrations.CreateModel(
            name='Poc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('comments', models.TextField(blank=True)),
                ('proj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Proj')),
            ],
        ),
        migrations.CreateModel(
            name='NetAddr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_address', models.CharField(max_length=50)),
                ('proj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Proj')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
                ('proj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Proj')),
            ],
        ),
        migrations.CreateModel(
            name='Attach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(max_length=256, upload_to='uploads/')),
                ('name', models.CharField(max_length=50)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('vuln', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Vuln')),
                ('webpage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.WebPage')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='sys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Sys'),
        ),
    ]
